name: chatter_gpt
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dart_openai: ^1.9.1
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  markdown_widget: ^2.1.0
  shared_preferences: ^2.0.20
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

